version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: idp-nginx
    tty: true
    restart: unless-stopped
    depends_on:
      - postgres
      - react
      - nestjs
    networks:
      - public
    ports:
      - 80:80
      - 443:443

  nestjs:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: idp-nestjs
    restart: always
    ports:
      - 5500:${NEST_PORT:-3000}
    depends_on:
      - postgres
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    stdin_open: true
    tty: true
    networks:
      - private
      - public

  postgres:
    image: postgres:13
    container_name: idp-postgres
    restart: always
    ports:
      - ${DB_PORT:-5432}:5432
    env_file:
      - ./api/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - private

  react:
    image: view
    build:
      context: ./view
      dockerfile: Dockerfile
    container_name: idp-react
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./view/.env.development
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    networks:
      - public

volumes:
  postgres:
    name: nest-db

networks:
  private:
  public:
