version: '3.9'

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    tty: true
    restart: unless-stopped
    depends_on:
      - db
      - view
      - api
    networks:
      - public
    ports:
      - 80:80
      - 443:443

  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:${NEST_PORT:-3000}
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - ./api/src:/app/src
    stdin_open: true
    tty: true
    networks:
      - private
      - public

  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - ${DB_PORT:-5432}:5432
    env_file:
      - ./api/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - private

  view:
    image: view
    build:
      context: ./view
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./view/.env.development
    volumes:
      - ./view/src:/app/src
    stdin_open: true
    tty: true
    networks:
      - public

volumes:
  postgres:
    name: nest-db

networks:
  private:
  public:
